"""Write the zoo's own cross-language parity bundles (ADR-0021, ADR-0032).

`generate.py` beside this trains tiny gaussian models for the *arithmetic* half of
the gate. This script writes the other half: the bundles for **`axon.strategies.zoo`'s
own families**, fitted on real candles, exported through the real registry path, and
frozen so that `cargo test` — not a scratch binary, and not pytest — is what proves
the zoo's artifacts cross into Rust.

Two properties are the entire point, and both are easy to lose:

**Nothing here touches the bytes after export.** ``export_artifact`` now writes the
version into the payload itself — ``axon_model_version`` for XGBoost's learner
attributes, ``model_version`` for ONNX — and it does so *before* the payload is
hashed. Every bundle the cross-language gate had ever run on was hand-stamped by
`generate.py`, so the gate that certifies the boundary had never once run on the path
it certifies. These two are the first that do. If a future edit here reaches for
``set_attr`` or ``proto.model_version``, it has removed the only reason this file
exists.

**It is reproducible from a clean clone.** The candles come from the committed
fixtures under ``python/axon/strategies/_fixtures/``, 900 m1 bars per coin, and *not*
from ``axon.strategies.data``'s cache — the cache is gitignored, so a bundle generated
from it could never be regenerated by anyone else, which is the same defect as a
reference nobody can reproduce. 900 bars is small, and small is fine: a 348-row
holdout proves a crossing exactly as well as a 15 000-row one, for the same reason a
three-tree stump proves a refusal. Reproducibility is verified rather than assumed —
two consecutive runs of this script produce byte-identical bundles, and the one family
that did not is held back below rather than committed with the churn.

Determinism comes from the zoo's own parameters rather than from anything set here —
``random_state=7`` on every family and ``n_jobs=1`` on XGBoost, whose histogram build
otherwise parallelizes with a non-deterministic reduction order. The families are used
**exactly as ``FAMILIES`` declares them**: fewer trees would make these bytes smaller
and would also make them a different model from the one ADR-0032's table describes.

Run from the repo root with the project venv:

    PYTHONPATH=python .venv/bin/python crates/axon-model/tests/bundles/generate_zoo.py

Like every generator in this directory it is deliberately not run by CI. Regenerating
a reference in the same breath as asserting it proves nothing — it would agree with
whatever Rust had just started doing. One field does move on every run whatever the
seeds do: ``git_sha`` records the commit that produced the artifact, so a regeneration
always shows a one-line manifest diff. That is true of every bundle already committed
here and it is a property of the format, not of this script.

**`sklearn_gbm` is deliberately absent.** It is the third family in the zoo, its bundle
writes cleanly, and `tract` refuses the bytes at load — ``attribute 'base_values':
expected length 1 (or undefined), got 2``. Promoting it would redden the default sweep
to record a refusal, which is what ``tests/refusals/`` is for. Its non-crossing is
pinned there and in ADR-0032, not here.
"""

from __future__ import annotations

import pathlib
import shutil
import tempfile

from axon.models import ModelRegistry
from axon.strategies import zoo
from axon.strategies.data import iter_fixtures
from axon.strategies.training import build_dataset

HERE = pathlib.Path(__file__).resolve().parent

#: The zoo families frozen here, named after the ``registry_id`` the zoo mints so a
#: manifest traces back to the run that produced it without guessing.
#:
#: ``logistic`` was held out of this tuple for one release cycle, and the reason is
#: worth keeping: ``skl2onnx.convert`` defaults its graph name to ``uuid4().hex``
#: (``skl2onnx/convert.py:180``), so two conversions of one fitted model differed in
#: ``graph.name`` and in nothing else — which gave the artifact a fresh
#: ``content_sha256`` every time and made the committed bytes something nobody else
#: could regenerate. ``axon.models.export`` now pins ``name="axon_sklearn"`` on that
#: call, mirroring the ``name="axon_lightgbm"`` it already passed to
#: ``convert_lightgbm``. Both routes are stable now, and ``main`` re-checks it here
#: rather than trusting that: the bundles are written twice and compared, because the
#: claim that put this family back is a *reproducibility* claim and the last one was
#: false.
CROSSING = ("xgboost", "logistic")

#: Bars of the final fold's test block to freeze. The block is 348 rows on the
#: committed fixtures, so this is not a binding cap today — it is here so that
#: regenerating against a longer history does not silently grow the committed
#: matrices by an order of magnitude.
HOLDOUT_ROWS = 512

#: Walk-forward folds, the zoo's own default. Stated because the *last* fold's model
#: is the one exported (ADR-0022: a refit on everything is a model no reported number
#: describes), so the fold count decides which rows the frozen holdout comes from.
FOLDS = 4


def build(name: str, dataset, into: pathlib.Path) -> str:
    """Fit, export and write one family's bundle into ``into``. Returns a one-line log.

    The registry is created per call and thrown away: the bundle carries the
    artifact's own bytes (ADR-0021 §4), so nothing downstream needs it to survive, and
    a fresh one makes ``next_version`` return 1 on every run rather than climbing.
    """
    fam = zoo.family(name)
    if not fam.crosses:
        raise SystemExit(
            f"{name} is declared not to cross; a bundle for it would redden the default sweep"
        )
    run = zoo.walk_forward(fam, dataset, folds=FOLDS)

    with tempfile.TemporaryDirectory() as tmp:
        registry = ModelRegistry(pathlib.Path(tmp) / "registry")
        # `export_family` calls `export_artifact`, which stamps the version into the
        # payload before hashing it. Nothing below re-opens the artifact.
        artifact = zoo.export_family(fam, run, registry, registry_id=f"zoo_{name}")

    bundle = zoo.rust_bundle(
        artifact, run.dataset.features[run.final_fold.test], out_dir=into, rows=HOLDOUT_ROWS
    )
    counts = bundle.manifest["decisions"]["counts"]
    if sum(1 for v in counts.values() if v) < 2:
        raise SystemExit(
            f"{name}: the holdout decides {counts}; a decision check that can only come out one "
            "way is a decoration, not a gate"
        )
    return (
        f"zoo_{name}: {artifact.ref} kind={artifact.meta.kind} "
        f"version={artifact.meta.version} payload={artifact.meta.content_bytes}B "
        f"rows={bundle.features.shape[0]} criterion={bundle.criterion} "
        f"score_space={bundle.manifest['score_space']} decisions={counts}"
    )


def main() -> None:
    candles = list(iter_fixtures(zoo.INTERVAL))
    if not candles:
        raise SystemExit(
            f"no committed {zoo.INTERVAL} fixtures; this script does not touch the gitignored "
            "candle cache, because a bundle nobody else can regenerate is not a frozen reference"
        )
    print(f"fixtures: {[(c.coin, len(c)) for c in candles]}")
    dataset = build_dataset(candles, spec=zoo.BAR_M1_V1, horizon=zoo.LABEL_HORIZON_BARS)
    print(f"dataset: {len(dataset)} rows x {dataset.features.shape[1]} features")

    # Built twice, into two staging roots, and compared before either is installed.
    #
    # This is not belt-and-braces. The `logistic` family was held out of `CROSSING`
    # for exactly one release cycle because its converter stamped a fresh uuid into
    # `graph.name` on every call, and *nothing noticed* — the bundle wrote, the gate
    # passed, and the artifact simply had a different content hash each time. A frozen
    # reference is a claim that these bytes are the bytes anyone re-running this gets,
    # and the only way to make that claim honestly is to check it here rather than to
    # believe the library. Two runs in one process share no state that matters: the
    # non-determinism it caught was per-conversion, not per-interpreter.
    with tempfile.TemporaryDirectory() as tmp:
        roots = [pathlib.Path(tmp) / "a", pathlib.Path(tmp) / "b"]
        logs: list[str] = []
        for i, root in enumerate(roots):
            for name in CROSSING:
                line = build(name, dataset, root / f"zoo_{name}")
                if i == 0:
                    logs.append(line)

        for name in CROSSING:
            first, second = (root / f"zoo_{name}" for root in roots)
            drifted = [
                p.name
                for p in sorted(first.iterdir())
                if p.read_bytes() != (second / p.name).read_bytes()
            ]
            if drifted:
                raise SystemExit(
                    f"zoo_{name}: two runs of this script disagree on {drifted}. The committed "
                    "bundle would be bytes nobody else can reproduce, so it is not written. "
                    "Find what is unseeded — a uuid in a graph name is the one that has bitten "
                    "us twice — rather than committing the first run and hoping."
                )
            out = HERE / f"zoo_{name}"
            shutil.rmtree(out, ignore_errors=True)
            shutil.copytree(first, out)

    for line in logs:
        print(line)
    print(f"reproducible: {len(CROSSING)} bundle(s) byte-identical across two builds")


if __name__ == "__main__":
    main()
