//! Generates `layout.rs` (offset/size constants) from the single source of truth,
//! `contracts/schema.toml`, at build time. The structs in `src/lib.rs` then assert
//! — at COMPILE time — that their field offsets match these constants, so any drift
//! between the schema and the Rust struct is a hard build error.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let schema_path = Path::new(&manifest_dir).join("../../contracts/schema.toml");
    println!("cargo:rerun-if-changed={}", schema_path.display());

    let text = fs::read_to_string(&schema_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", schema_path.display()));
    let doc: toml::Value = toml::from_str(&text).expect("contracts/schema.toml is not valid TOML");

    let mut out = String::new();
    out.push_str(
        "// @generated by axon-contracts/build.rs from contracts/schema.toml — DO NOT EDIT.\n\n",
    );

    // ── top-level + fixed point ──
    emit(
        &mut out,
        "SCHEMA_VERSION",
        "u8",
        req_int(&doc, "schema_version"),
    );
    let fp = doc.get("fixed_point").expect("[fixed_point]");
    emit(
        &mut out,
        "FIXED_POINT_DECIMALS",
        "u32",
        req_int(fp, "decimals"),
    );
    emit(&mut out, "FIXED_POINT_SCALE", "i64", req_int(fp, "scale"));

    // ── signal ──
    let sig = doc.get("signal").expect("[signal]");
    emit_usize(&mut out, "SIGNAL_SIZE", req_int(sig, "size"));
    emit_usize(&mut out, "SIGNAL_ALIGN", req_int(sig, "align"));

    let kinds = sig.get("kinds").expect("[signal.kinds]");
    emit(
        &mut out,
        "KIND_TARGET_POSITION",
        "u8",
        req_int(kinds, "target_position"),
    );

    let flags = sig.get("flags").expect("[signal.flags]");
    emit(
        &mut out,
        "FLAG_REDUCE_ONLY",
        "u16",
        req_int(flags, "reduce_only"),
    );
    emit(&mut out, "FLAG_CLOSE", "u16", req_int(flags, "close"));

    for f in req_array(sig, "fields") {
        let name = req_str(f, "name").to_uppercase();
        emit_usize(&mut out, &format!("OFF_{name}"), req_int(f, "offset"));
        emit_usize(&mut out, &format!("SZ_{name}"), req_int(f, "size"));
    }

    // ── md_slice ──
    // Offsets are `MD_OFF_*`, not `OFF_*`: the two records share six field names
    // (`seq`, `ts_event`, `symbol_id`, `flags`, `schema_version`, `kind`, …), so an
    // unprefixed constant would be silently overwritten by whichever record is
    // emitted last — and the compile-time offset asserts would then be checking one
    // struct against the other's layout.
    let md = doc.get("md_slice").expect("[md_slice]");
    emit_usize(&mut out, "MD_SLICE_SIZE", req_int(md, "size"));
    emit_usize(&mut out, "MD_SLICE_ALIGN", req_int(md, "align"));
    emit(
        &mut out,
        "MD_SLICE_SCHEMA_VERSION",
        "u8",
        req_int(md, "schema_version"),
    );

    let md_kinds = md.get("kinds").expect("[md_slice.kinds]");
    emit(&mut out, "MD_KIND_QUOTE", "u8", req_int(md_kinds, "quote"));
    emit(&mut out, "MD_KIND_TRADE", "u8", req_int(md_kinds, "trade"));
    emit(
        &mut out,
        "MD_KIND_SNAPSHOT",
        "u8",
        req_int(md_kinds, "snapshot"),
    );

    let md_flags = md.get("flags").expect("[md_slice.flags]");
    emit(
        &mut out,
        "MD_FLAG_LAST_TRADE_SELL",
        "u16",
        req_int(md_flags, "last_trade_sell"),
    );

    for f in req_array(md, "fields") {
        let name = req_str(f, "name").to_uppercase();
        emit_usize(&mut out, &format!("MD_OFF_{name}"), req_int(f, "offset"));
        emit_usize(&mut out, &format!("MD_SZ_{name}"), req_int(f, "size"));
    }

    // ── md_bar ──
    // `MD_BAR_OFF_*` for the same reason `MD_OFF_*` exists: `MdBar` shares eight
    // field names with `MdSlice` (`seq`, `ts_event`, `open`/`close` against nothing,
    // `symbol_id`, `flags`, `schema_version`, `kind`, `reserved`), and an unprefixed
    // constant would be overwritten by whichever record is emitted last — which would
    // leave the compile-time offset asserts checking one struct against the other's
    // layout, the exact silent-corruption class this file exists to prevent.
    let bar = doc.get("md_bar").expect("[md_bar]");
    emit_usize(&mut out, "MD_BAR_SIZE", req_int(bar, "size"));
    emit_usize(&mut out, "MD_BAR_ALIGN", req_int(bar, "align"));
    emit(
        &mut out,
        "MD_BAR_SCHEMA_VERSION",
        "u8",
        req_int(bar, "schema_version"),
    );

    let bar_kinds = bar.get("kinds").expect("[md_bar.kinds]");
    emit(
        &mut out,
        "MD_BAR_KIND_CLOSED",
        "u8",
        req_int(bar_kinds, "closed"),
    );

    let bar_flags = bar.get("flags").expect("[md_bar.flags]");
    emit(
        &mut out,
        "MD_BAR_FLAG_GAP_BEFORE",
        "u16",
        req_int(bar_flags, "gap_before"),
    );
    emit(
        &mut out,
        "MD_BAR_FLAG_FIRST_BAR",
        "u16",
        req_int(bar_flags, "first_bar"),
    );

    for f in req_array(bar, "fields") {
        let name = req_str(f, "name").to_uppercase();
        emit_usize(
            &mut out,
            &format!("MD_BAR_OFF_{name}"),
            req_int(f, "offset"),
        );
        emit_usize(&mut out, &format!("MD_BAR_SZ_{name}"), req_int(f, "size"));
    }

    // ── ring ──
    let ring = doc.get("ring").expect("[ring]");
    let magic = req_int(ring, "magic") as u64; // stored as a positive hex int that fits i64
    out.push_str(&format!("pub const RING_MAGIC: u64 = {magic};\n"));
    emit(&mut out, "RING_VERSION", "u32", req_int(ring, "version"));
    emit_usize(&mut out, "RING_CACHE_LINE", req_int(ring, "cache_line"));
    emit_usize(&mut out, "RING_HEADER_SIZE", req_int(ring, "header_size"));
    let ring_kinds = ring.get("record_kinds").expect("[ring.record_kinds]");
    emit(
        &mut out,
        "RING_KIND_SIGNAL",
        "u32",
        req_int(ring_kinds, "signal"),
    );
    emit(
        &mut out,
        "RING_KIND_MD_SLICE",
        "u32",
        req_int(ring_kinds, "md_slice"),
    );
    emit(
        &mut out,
        "RING_KIND_MD_BAR",
        "u32",
        req_int(ring_kinds, "md_bar"),
    );
    for f in req_array(ring, "header_fields") {
        let name = req_str(f, "name").to_uppercase();
        emit_usize(&mut out, &format!("RING_OFF_{name}"), req_int(f, "offset"));
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("layout.rs"), out).expect("write layout.rs");
}

fn emit(out: &mut String, name: &str, ty: &str, val: i64) {
    out.push_str(&format!("pub const {name}: {ty} = {val};\n"));
}

fn emit_usize(out: &mut String, name: &str, val: i64) {
    assert!(val >= 0, "{name} must be non-negative, got {val}");
    out.push_str(&format!("pub const {name}: usize = {val};\n"));
}

fn req_int(v: &toml::Value, key: &str) -> i64 {
    v.get(key)
        .and_then(|x| x.as_integer())
        .unwrap_or_else(|| panic!("expected integer key `{key}`"))
}

fn req_str<'a>(v: &'a toml::Value, key: &str) -> &'a str {
    v.get(key)
        .and_then(|x| x.as_str())
        .unwrap_or_else(|| panic!("expected string key `{key}`"))
}

fn req_array<'a>(v: &'a toml::Value, key: &str) -> &'a [toml::Value] {
    v.get(key)
        .and_then(|x| x.as_array())
        .unwrap_or_else(|| panic!("expected array key `{key}`"))
        .as_slice()
}
