"""Write the committed feature-parity bundles the Rust gate runs on.

A *feature parity bundle* is the frozen cross-language question ADR-0035 defines:
a `FeatureSpec`, the input arrays it reads, and the matrix **Python** computed from
them, in a directory `axon_features::parity::FeatureBundle` opens with no Python, no
numpy, no network and no clock. This script writes the ones that are committed.

The sibling of `crates/axon-model/tests/bundles/generate.py`, and it follows the same
rule: **regenerating rewrites frozen references, and the git diff IS the review.**

## What each bundle is for, and why there is more than one

**`bar_m1_btc` and `bar_m1_eth`** — `BAR_M1_V1` over the committed venue fixtures in
`axon/strategies/_fixtures`. These are verbatim `candleSnapshot` rows, not a
resampling or a reconstruction, so a gate that passes here passes against numbers
Hyperliquid actually printed. Two coins rather than one because the transforms are
scale-free and a single instrument cannot show that: BTC and ETH differ by an order
of magnitude in price, which is exactly where a normalization mistake would hide.

**`bar_m1_testnet_live`** — the same spec over the **58 m1 bars that crossed a live
Hyperliquid testnet socket** during the ADR-0029 shadow run: the venue's own frames,
through the Rust publisher, onto the `MdBar` ring, read back by Python. It is by far
the smallest bundle and by far the best provenance in the tree, and it carries the
two live pathologies no offline history has: **`clv` is NaN whenever every trade in a
minute happens at one price** (6 of those 58 bars, against 0 in the committed 800-bar
hourly fixtures), and the venue simply **omits a bar for a minute with no trades**, so the
series has real gaps. Both are things a synthetic corpus would never produce and both
are exactly where a NaN rule earns its keep.

**`perp_core_live`** — `PERP_CORE_V1` over a **recorded order book and tape**: 675
market-data slices from a live read-only Hyperliquid testnet session, venue frames →
Rust core → `MdPublisher` → the `MdSlice` ring → `md_slice_inputs`. This is the only
committed corpus whose microstructure columns are a venue's rather than derived, which is
what makes the nine columns of the reference perp spec — mid, spread, book imbalance,
trade-flow imbalance and the EMA crossover — gated against real book state.

**It is not regenerated by this script**, and that is deliberate rather than an omission:
it needs a live socket, and a generator that silently produced a synthetic stand-in under
the same name would be a fixture lying about its provenance. It was made by running a
read-only session with `session.feeds = ["Bbo", "L2Book", "Trades", "Ticker"]` and
`[md_ring] policy = "every_update"`, draining the slice ring with **exactly one**
consumer (an SPSC ring has one; two readers steal from each other and each reports the
other's reads as drops), filtering to one `symbol_id`, and calling
`write_feature_bundle(PERP_CORE_V1, md_slice_inputs(slices)[0], ...)`. One instrument
only: a spec is computed over a *sequence*, and two symbols interleaved on one ring are
two sequences — a 32-sample statistic of alternating BTC and ETH prices is not a feature
of anything. **A bar-only session will not do**: without a `Trades` subscription every
slice carries `trade_sz = 0`, `trade_flow_imbalance` is NaN on every row, and the writer
correctly refuses a corpus that never finishes warming up.

**`all_transforms`** — a spec that exists to be gated rather than to be traded. The
shipped specs between them exercise **eleven** of the seventeen registered transforms
(`BAR_M1_V1`'s six and `PERP_CORE_V1`'s nine, overlapping on four);
this one names all seventeen, so the cross-language gate covers the library rather
than covering the subset a strategy happened to pick. It is honest about what it is:
`spec` name `feature_gate_coverage`, never registered anywhere, never fitted, and
carrying an EMA precisely *because* the shipped bar spec cannot. Its book and tape
columns are derived from the same real bars rather than invented — see
`_book_from_bars` for exactly what that means and what it does not claim.

## Two things that are not obvious

**Every bundle goes through `axon.features.bar_inputs`**, which is the one place a
fixed-point integer becomes a float. A generator that divided by `1e8` itself would
be a second decoder, and the two agree on the day they are written.

**The reference is computed over the bytes read back off disk**, not over the
in-memory matrix — `write_feature_bundle` does that, and it is the line that makes
the recorded answer by construction the answer to the question Rust asks.
"""

from __future__ import annotations

import csv
import shutil
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
sys.path.insert(0, str(ROOT / "python"))

from axon.features import bar_inputs  # noqa: E402
from axon.features.spec import (  # noqa: E402
    BAR_M1_V1,
    PERP_CORE_V1,
    FeatureDef,
    FeatureSpec,
)
from axon.parity.feature_bundle import read_feature_bundle, write_feature_bundle  # noqa: E402
from axon.strategies.data import fixture_candles  # noqa: E402

#: The 58 bars from the ADR-0029 shadow run. Under `/data/`, which is `.gitignore`d,
#: so this path is the *provenance* of the bundle rather than a dependency of it: the
#: values themselves are committed inside `inputs.f64`, which is the whole point of a
#: bundle being self-contained. If the file is gone, that bundle is left alone rather
#: than regenerated from something else wearing its name.
TESTNET_BARS = ROOT / "data/captures/p5-shadow-m1-bars.csv"


def _bars_from_fixture(coin: str) -> dict[str, np.ndarray]:
    """Committed venue rows → the named arrays a bar spec reads."""
    candles = fixture_candles(coin, "1m")
    return candles.feature_inputs()


def _bars_from_testnet_csv(path: Path) -> dict[str, np.ndarray]:
    """The shadow run's own CSV → the same named arrays, through the same decoder.

    The CSV is this repo's writing rather than the venue's, and it holds the
    fixed-point integers the ring carried. Only the *parsing* is local; the scaling
    still happens exactly once, in `bar_inputs`, which is the rule that keeps a
    research path and a serving path from disagreeing about where the decimal point
    is by eight orders of magnitude.
    """
    with path.open(encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    cols = {
        name: np.array([int(r[name]) for r in rows], dtype=np.int64)
        for name in ("open", "high", "low", "close", "volume")
    }
    return bar_inputs(cols["open"], cols["high"], cols["low"], cols["close"], cols["volume"])


def _book_from_bars(bars: dict[str, np.ndarray]) -> dict[str, np.ndarray]:
    """Book and tape columns derived from real bars, for the coverage spec.

    **Read what this is and is not.** These are not a real order book: nobody
    recorded the touch at each of these minutes, and a bundle claiming otherwise
    would be a fixture lying about its provenance. What they *are* is a set of
    columns with the shape the microstructure transforms have to survive — a real
    price level, a spread that varies with the bar's own range, sizes that go to zero
    (the empty-book branch), and a trade sign that is zero on some observations (the
    quote-only branch every `MdSlice` produces between prints).

    That is enough for what this bundle is for. The gate asks whether the two
    languages compute the same numbers from the same inputs; it does not ask whether
    the inputs are a market. Realism buys nothing here and a false provenance claim
    costs everything, which is why the manifest's `source.description` says
    "derived from" and names this function.
    """
    close, high, low = bars["close"], bars["high"], bars["low"]
    n = close.size
    half = (high - low) / 4.0
    bid = close - half
    ask = close + half
    # A zero on both sides periodically: the empty-book branch of `book_imbalance`
    # and `mid_price` is the one that must come back NaN rather than "balanced", and
    # a corpus that never hits it leaves that branch ungated.
    #
    # The period has to be **longer than the longest window in the spec**, and that
    # is not a tuning choice — it is the difference between a bundle and nothing. A
    # NaN mid propagates through every rolling column that reads it, so a gap every
    # seven observations against a 16-sample volatility means *no row anywhere* has
    # every column finite. The writer refuses such a corpus outright, and rightly:
    # an all-NaN reference compares bit-exactly against an all-NaN candidate, so the
    # bundle would pass for a runtime that computes nothing at all. 97 is prime and
    # comfortably past the 17 observations `vol_16` reaches back through, so the gap
    # is exercised and the corpus still warms up between gaps.
    idx = np.arange(n)
    empty = idx % 97 == 0
    bid = np.where(empty, 0.0, bid)
    ask = np.where(empty, 0.0, ask)
    bid_sz = np.where(empty, 0.0, 1.0 + (idx % 5))
    ask_sz = np.where(empty, 0.0, 1.0 + ((idx + 2) % 5))
    # Zero on a quote-only observation, which is what every slice between prints
    # carries. `np.sign` keeps it zero; `f64::signum` would turn it into a one-lot
    # buy, and that is the difference this column exists to gate.
    trade_sz = np.where(idx % 3 == 0, 0.0, bars["volume"])
    trade_sign = np.where(idx % 3 == 0, 0.0, np.where(idx % 2 == 0, 1.0, -1.0))
    return {
        "bid_px": bid,
        "ask_px": ask,
        "bid_sz": bid_sz,
        "ask_sz": ask_sz,
        "trade_sz": trade_sz,
        "trade_sign": trade_sign,
    }


#: Every registered transform, exactly once. Not a strategy and never registered as
#: one: it exists so the cross-language gate covers the *library* rather than the
#: subset a shipped spec happens to use. `test_generate_covers_every_transform` in
#: the Rust gate asserts the coverage claim rather than trusting this comment.
COVERAGE_SPEC = FeatureSpec(
    name="feature_gate_coverage",
    version=1,
    features=(
        # Microstructure, straight off the book columns.
        FeatureDef("mid", "mid_price"),
        FeatureDef("spread_abs", "spread"),
        FeatureDef("spread_bps", "relative_spread"),
        FeatureDef("book_imb", "book_imbalance"),
        FeatureDef("tfi_16", "trade_flow_imbalance", params={"window": 16}),
        # Bars.
        FeatureDef("range_bps", "relative_range"),
        FeatureDef("clv", "close_location"),
        # Returns and momentum, over a column produced above — which is what makes
        # this bundle exercise the *composition* rule and not only the transforms.
        FeatureDef("ret_1", "log_return", params={"period": 1}, inputs={"price": "mid"}),
        FeatureDef("mom_8", "momentum", params={"window": 8}, inputs={"price": "mid"}),
        FeatureDef(
            "vol_16", "realized_volatility", params={"window": 16}, inputs={"price": "mid"}
        ),
        # The four rolling primitives, named directly rather than only through the
        # composites, so a break in one is attributable.
        FeatureDef("mean_12", "rolling_mean", params={"window": 12}, inputs={"x": "mid"}),
        FeatureDef("std_12", "rolling_std", params={"window": 12}, inputs={"x": "mid"}),
        FeatureDef("sum_12", "rolling_sum", params={"window": 12}, inputs={"x": "trade_sz"}),
        FeatureDef("z_12", "rolling_zscore", params={"window": 12}, inputs={"x": "mid"}),
        # `ddof=1` somewhere, because the default is 0 and a parameter that is never
        # set on either side is a parameter neither side is gated on.
        FeatureDef(
            "std_12_s", "rolling_std", params={"window": 12, "ddof": 1}, inputs={"x": "mid"}
        ),
        # The finite-lookback crossover, and the two unbounded transforms. The EMA
        # pair is here *because* `BAR_M1_V1` cannot carry one: the batch path must
        # compute it faithfully even though `FeatureStream` refuses to serve it, and
        # nothing else in the committed set would gate that.
        FeatureDef("sma_x_4_12", "sma_crossover", params={"fast": 4, "slow": 12}, inputs={"price": "mid"}),
        FeatureDef("ema_8", "ema", params={"span": 8}, inputs={"x": "mid"}),
        FeatureDef("ema_x_4_12", "ema_crossover", params={"fast": 4, "slow": 12}, inputs={"price": "mid"}),
    ),
)


def write(name: str, spec: FeatureSpec, inputs: dict[str, np.ndarray], source: dict) -> None:
    out = HERE / name
    if out.exists():
        # Removed rather than written over: `write_feature_bundle` refuses to clobber
        # without `overwrite=True`, and a partially-overwritten directory holding one
        # new matrix beside one stale one is the state the manifest-last rule exists
        # to make legible. Starting clean means the only bundle that can exist here
        # is one this run wrote in full.
        shutil.rmtree(out)
    write_feature_bundle(spec, inputs, out_dir=out, source=source)

    # Read it back through the reader that will police it. A bundle that its own
    # reader refuses has no business being committed, and finding that out here beats
    # finding it out from a red Rust gate that says nothing about which side is wrong.
    bundle = read_feature_bundle(out)
    finite = int(bundle.manifest["features"]["finite_rows"])
    nan_cells = int(bundle.manifest["features"]["nan_cells"])
    print(
        f"  {name:22s} {bundle.spec_ref:34s} "
        f"{bundle.rows:5d} rows x {len(bundle.columns)} cols  "
        f"finite {finite}  nan_cells {nan_cells}  libm {list(bundle.libm_columns)}"
    )


def main() -> None:
    print("feature-parity bundles (ADR-0035) — regenerating rewrites frozen references")

    for coin in ("BTC", "ETH"):
        bars = _bars_from_fixture(coin)
        write(
            f"bar_m1_{coin.lower()}",
            BAR_M1_V1,
            bars,
            {
                "description": (
                    "verbatim Hyperliquid candleSnapshot rows, committed at "
                    "python/axon/strategies/_fixtures"
                ),
                "instrument": coin,
                "interval": "1m",
                "venue": "hyperliquid-mainnet",
            },
        )

    if TESTNET_BARS.is_file():
        bars = _bars_from_testnet_csv(TESTNET_BARS)
        write(
            "bar_m1_testnet_live",
            BAR_M1_V1,
            bars,
            {
                "description": (
                    "bars that crossed a live Hyperliquid testnet socket during the "
                    "ADR-0029 shadow run: venue frames -> Rust MdPublisher -> MdBar "
                    "ring -> Python. Carries the two live pathologies no offline "
                    "history has: a NaN clv on a minute that traded at one price, "
                    "and gaps where the venue sent no frame at all"
                ),
                "instrument": "BTC",
                "interval": "1m",
                "venue": "hyperliquid-testnet",
            },
        )
    else:
        # Loud rather than silent: a missing tape means this run wrote one fewer
        # bundle than the committed set, and a regeneration that quietly dropped the
        # only live-provenance fixture would show up as a deletion in the diff with
        # no explanation attached to it.
        print(f"  SKIPPED bar_m1_testnet_live: {TESTNET_BARS} is not present")

    bars = _bars_from_fixture("BTC")
    coverage = dict(bars)
    coverage.update(_book_from_bars(bars))
    write(
        "all_transforms",
        COVERAGE_SPEC,
        coverage,
        {
            "description": (
                "every registered transform, exactly once, so the gate covers the "
                "library rather than the subset a shipped spec uses. Bars are real "
                "committed venue rows; the book and tape columns are DERIVED from "
                "them by generate.py::_book_from_bars and are not a recorded book"
            ),
            "instrument": "BTC",
            "interval": "1m",
            "venue": "hyperliquid-mainnet + derived",
        },
    )

    # `perp_core_live` is not written here (see the module docstring: it needs a live
    # socket) and must not be deleted by a regeneration either — `write` removes only the
    # directories it is about to rewrite.
    if not (HERE / "perp_core_live").is_dir():
        print("  NOTE  perp_core_live is absent; it is recorded, not generated — see the docstring")

    covered = {d.feature for d in COVERAGE_SPEC.features}
    covered |= {d.feature for d in BAR_M1_V1.features}
    covered |= {d.feature for d in PERP_CORE_V1.features}
    from axon.features.registry import registered_features

    missing = sorted(set(registered_features()) - covered)
    print(f"transforms covered by the committed set: {len(covered)}/{len(registered_features())}")
    if missing:
        raise SystemExit(f"NOT COVERED by any committed bundle: {missing}")


if __name__ == "__main__":
    main()
